### ISSUE TITLE
Guru 8000000B when running on PiStorm32Lite

### ISSUE THREAD

**Issue by Andiweli** [AmigaPorts/ioq3#15]
Have some issue here getting this running on my A1200 with PiStorm32Lite.
The game loads from HDD, and after a few secons I get a popup with GURU 8000000B.
Only thing I can do is ignore (ends game) or reboot.

**Comment by Cowcat5150** [comment]
Sorry, didn't read this issue till now.

I assume you're talking about the 68k port running on PiStorm. For what I understand the guru means a CPU/FPU situation or basically something missing in the FPU department. The 68k builds are compiled with vbcc for 060 CPU's and proper FPU support for those.

Does your system run W3D programs/demos ?  Last time I tried in winuae it worked.

**Comment by Andiweli** [comment]
Nevermind... got it working recently with Wazp3D.
Absolutely unplayable with Pistorm32... 1 Frame per Second or so.
Think this needs a decent "real" graphics card with 3D :)
